trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  JAVA_VARA: ${javaHomeOption}


steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: ${JAVA_VARA}
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    goals: 'package'
